language: php
php:
  - '7.1'

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover=build/logs/clover.xml tests

after_script:
  - php vendor/bin/coveralls -v
